
-----POC table measuring glass available vs glass required for all three bars

CREATE TABLE 
ny_results
(Date1 VARCHAR(50), 
Hours1 VARCHAR(50),
Glass_Type VARCHAR(50),
Actual_Glass_Required VARCHAR(50),
Actual_Present_in_Bar VARCHAR(50));

CREATE TABLE 
bp_results
(Date1 VARCHAR(50), 
Hours1 VARCHAR(50),
Glass_Type VARCHAR(50),
Actual_Glass_Required	 VARCHAR(50),
Actual_Present_in_Bar VARCHAR(50));

CREATE TABLE ln_results(Date1 VARCHAR(50), 
Hours1 VARCHAR(50),
Glass_Type VARCHAR(50),
Actual_Glass_Required	 VARCHAR(50),
Actual_Present_in_Bar VARCHAR(50));


